backend:
  name: "git-gateway"
  accept_roles:
    - "admin"
    - "editor"
media_folder: "static/images"
collections:
  - name: "pages"
    label: "Pages"
    folder: "site/pages"
    identifier_field: "title"
    extension: "md"
    create: false
    delete: false
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Layout"
        widget: "hidden"
        name: "layout"
        default: "{{slug}}.html"
      - label: "Seo"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Open Graph Image"
            name: "og:image"
            widget: "image"
            required: false
            media_library:
              config:
                multiple: false
          - label: "Twitter Card"
            name: "twitter:card"
            widget: "string"
            default: "summary"
            required: false
          - label: "Twitter Site"
            name: "twitter:site"
            widget: "string"
            required: false
          - label: "Twitter Creator"
            name: "twitter:creator"
            widget: "string"
            required: false
          - label: "Additional HTML tags"
            name: "additional_tags"
            widget: "text"
            required: false
  - name: "project"
    label: "Projects"
    folder: "site/project"
    create: true
    identifier_field: "name"
    extension: "md"
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Tags"
        widget: "hidden"
        name: "tags"
        default: "project"
      - label: "Layout"
        widget: "hidden"
        name: "layout"
        default: "single-project.html"
      - label: "Seo"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Open Graph Image"
            name: "og:image"
            widget: "image"
            required: false
            media_library:
              config:
                multiple: false
          - label: "Twitter Card"
            name: "twitter:card"
            widget: "string"
            default: "summary"
            required: false
          - label: "Twitter Site"
            name: "twitter:site"
            widget: "string"
            required: false
          - label: "Twitter Creator"
            name: "twitter:creator"
            widget: "string"
            required: false
          - label: "Additional HTML tags"
            name: "additional_tags"
            widget: "text"
            required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
      - name: "project-summary"
        label: "Project Summary"
        widget: "text"
        required: false
      - widget: "object"
        name: "main-project-image"
        label: "Main Project Image"
        fields:
          - widget: "image"
            name: "url"
            label: "Image"
            allow_multiple: false
            required: false
          - widget: "string"
            name: "alt"
            label: "Alt Text"
            required: false
      - name: "project-type"
        label: "Project Type"
        widget: "string"
        required: false
      - widget: "list"
        name: "project-gallery"
        label: "Project Gallery"
        fields:
          - widget: "image"
            name: "url"
            label: "Image"
            allow_multiple: false
            required: false
          - widget: "string"
            name: "alt"
            label: "Alt Text"
            required: false
      - widget: "relation"
        collection: "category"
        value_field: "site/category/{{slug}}.md"
        search_fields:
          - "slug"
          - "name"
        display_fields:
          - "name"
        required: false
        name: "type"
      - name: "link"
        label: "Link (URL)"
        widget: "string"
        required: false
      - name: "other-field"
        label: "Other Field"
        widget: "string"
        required: false
      - name: "github-link"
        label: "Github Link (URL)"
        widget: "string"
        required: false
      - name: "name"
        label: "Name"
        widget: "string"
        required: true
      - name: "created-on"
        label: "Created On"
        widget: "datetime"
        required: false
      - name: "updated-on"
        label: "Updated On"
        widget: "datetime"
        required: false
      - name: "published-on"
        label: "Published On"
        widget: "datetime"
        required: false
  - name: "post"
    label: "Blog Posts"
    folder: "site/post"
    create: true
    identifier_field: "name"
    extension: "md"
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Tags"
        widget: "hidden"
        name: "tags"
        default: "post"
      - label: "Layout"
        widget: "hidden"
        name: "layout"
        default: "single-post.html"
      - label: "Seo"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Open Graph Image"
            name: "og:image"
            widget: "image"
            required: false
            media_library:
              config:
                multiple: false
          - label: "Twitter Card"
            name: "twitter:card"
            widget: "string"
            default: "summary"
            required: false
          - label: "Twitter Site"
            name: "twitter:site"
            widget: "string"
            required: false
          - label: "Twitter Creator"
            name: "twitter:creator"
            widget: "string"
            required: false
          - label: "Additional HTML tags"
            name: "additional_tags"
            widget: "text"
            required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
      - name: "date"
        label: "Date"
        widget: "datetime"
        required: false
      - name: "subheader"
        label: "Subheader"
        widget: "string"
        required: false
      - name: "name"
        label: "Name"
        widget: "string"
        required: true
      - name: "created-on"
        label: "Created On"
        widget: "datetime"
        required: false
      - name: "updated-on"
        label: "Updated On"
        widget: "datetime"
        required: false
      - name: "published-on"
        label: "Published On"
        widget: "datetime"
        required: false
  - name: "category"
    label: "Project Categories"
    folder: "site/category"
    create: true
    identifier_field: "name"
    extension: "md"
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Tags"
        widget: "hidden"
        name: "tags"
        default: "category"
      - label: "Layout"
        widget: "hidden"
        name: "layout"
        default: "single-category.html"
      - label: "Seo"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Open Graph Image"
            name: "og:image"
            widget: "image"
            required: false
            media_library:
              config:
                multiple: false
          - label: "Twitter Card"
            name: "twitter:card"
            widget: "string"
            default: "summary"
            required: false
          - label: "Twitter Site"
            name: "twitter:site"
            widget: "string"
            required: false
          - label: "Twitter Creator"
            name: "twitter:creator"
            widget: "string"
            required: false
          - label: "Additional HTML tags"
            name: "additional_tags"
            widget: "text"
            required: false
      - name: "name"
        label: "Name"
        widget: "string"
        required: true
      - name: "created-on"
        label: "Created On"
        widget: "datetime"
        required: false
      - name: "updated-on"
        label: "Updated On"
        widget: "datetime"
        required: false
      - name: "published-on"
        label: "Published On"
        widget: "datetime"
        required: false
  - name: "partners"
    label: "Partners"
    folder: "site/partners"
    create: true
    identifier_field: "name"
    extension: "md"
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Tags"
        widget: "hidden"
        name: "tags"
        default: "partners"
      - label: "Layout"
        widget: "hidden"
        name: "layout"
        default: "single-partners.html"
      - label: "Seo"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Open Graph Image"
            name: "og:image"
            widget: "image"
            required: false
            media_library:
              config:
                multiple: false
          - label: "Twitter Card"
            name: "twitter:card"
            widget: "string"
            default: "summary"
            required: false
          - label: "Twitter Site"
            name: "twitter:site"
            widget: "string"
            required: false
          - label: "Twitter Creator"
            name: "twitter:creator"
            widget: "string"
            required: false
          - label: "Additional HTML tags"
            name: "additional_tags"
            widget: "text"
            required: false
      - widget: "object"
        name: "image"
        label: "Image"
        fields:
          - widget: "image"
            name: "url"
            label: "Image"
            allow_multiple: false
            required: false
          - widget: "string"
            name: "alt"
            label: "Alt Text"
            required: false
      - name: "name"
        label: "Name"
        widget: "string"
        required: true
      - name: "created-on"
        label: "Created On"
        widget: "datetime"
        required: false
      - name: "updated-on"
        label: "Updated On"
        widget: "datetime"
        required: false
      - name: "published-on"
        label: "Published On"
        widget: "datetime"
        required: false
  - name: "newsletter"
    label: "Newsletters"
    folder: "site/newsletter"
    create: true
    identifier_field: "name"
    extension: "md"
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Tags"
        widget: "hidden"
        name: "tags"
        default: "newsletter"
      - label: "Layout"
        widget: "hidden"
        name: "layout"
        default: "single-newsletter.html"
      - label: "Seo"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Open Graph Image"
            name: "og:image"
            widget: "image"
            required: false
            media_library:
              config:
                multiple: false
          - label: "Twitter Card"
            name: "twitter:card"
            widget: "string"
            default: "summary"
            required: false
          - label: "Twitter Site"
            name: "twitter:site"
            widget: "string"
            required: false
          - label: "Twitter Creator"
            name: "twitter:creator"
            widget: "string"
            required: false
          - label: "Additional HTML tags"
            name: "additional_tags"
            widget: "text"
            required: false
      - name: "link"
        label: "Link (URL)"
        widget: "string"
        required: false
      - name: "published-date"
        label: "Published Date"
        widget: "datetime"
        required: false
      - name: "name"
        label: "Name"
        widget: "string"
        required: true
      - name: "created-on"
        label: "Created On"
        widget: "datetime"
        required: false
      - name: "updated-on"
        label: "Updated On"
        widget: "datetime"
        required: false
      - name: "published-on"
        label: "Published On"
        widget: "datetime"
        required: false
